library(testthat)

# Test helper functions
test_that("get_fomc_day_within_fomc_cycle returns expected values", {
  fomc_test_date <- as.Date("2014-01-28")
  
  expect_equal(get_fomc_day_within_fomc_cycle(fomc_test_date, as.Date("2014-01-21")), -5)
  expect_equal(get_fomc_day_within_fomc_cycle(fomc_test_date, as.Date("2014-01-22")), -4)
  expect_equal(get_fomc_day_within_fomc_cycle(fomc_test_date, as.Date("2014-01-23")), -3)
  expect_equal(get_fomc_day_within_fomc_cycle(fomc_test_date, as.Date("2014-01-24")), -2)
  expect_equal(get_fomc_day_within_fomc_cycle(fomc_test_date, as.Date("2014-01-25")), NULL)
  expect_equal(get_fomc_day_within_fomc_cycle(fomc_test_date, as.Date("2014-01-26")), NULL)
  expect_equal(get_fomc_day_within_fomc_cycle(fomc_test_date, as.Date("2014-01-27")), -1)
  expect_equal(get_fomc_day_within_fomc_cycle(fomc_test_date, as.Date("2014-01-28")), 0)
  expect_equal(get_fomc_day_within_fomc_cycle(fomc_test_date, as.Date("2014-01-29")), 1)
  expect_equal(get_fomc_day_within_fomc_cycle(fomc_test_date, as.Date("2014-01-30")), 2)
  expect_equal(get_fomc_day_within_fomc_cycle(fomc_test_date, as.Date("2014-01-31")), 3)
  expect_equal(get_fomc_day_within_fomc_cycle(fomc_test_date, as.Date("2014-02-01")), NULL)
  expect_equal(get_fomc_day_within_fomc_cycle(fomc_test_date, as.Date("2014-02-02")), NULL)
  expect_equal(get_fomc_day_within_fomc_cycle(fomc_test_date, as.Date("2014-02-03")), 4)
  expect_equal(get_fomc_day_within_fomc_cycle(fomc_test_date, as.Date("2014-02-04")), 5)
  expect_equal(get_fomc_day_within_fomc_cycle(fomc_test_date, as.Date("2014-02-05")), 6)
  expect_equal(get_fomc_day_within_fomc_cycle(fomc_test_date, as.Date("2014-02-06")), 7)
  expect_equal(get_fomc_day_within_fomc_cycle(fomc_test_date, as.Date("2014-02-07")), 8)
  expect_equal(get_fomc_day_within_fomc_cycle(fomc_test_date, as.Date("2014-02-08")), NULL)
  expect_equal(get_fomc_day_within_fomc_cycle(fomc_test_date, as.Date("2014-02-09")), NULL)
  expect_equal(get_fomc_day_within_fomc_cycle(fomc_test_date, as.Date("2014-02-10")), 9)
  expect_equal(get_fomc_day_within_fomc_cycle(fomc_test_date, as.Date("2014-02-11")), 10)
})